@url=http://localhost:7122

### Login User
Post {{url}}/login
Content-Type: application/json

{
    "name":"Matthias",
    "password":"aA@123456"
}

### Post New User
Post {{url}}/user/create
Content-Type: application/json

{
    "name":"Matthias",
    "email":"maze@online.de",
    "password":"aA@123456"
}
### Get Items of User
Post {{url}}/getItem
Content-Type: application/json

{
    "id":"62f4013cb7fcb386648da55c"
}

### Post new Item
Post {{url}}/item
Content-Type: application/json

{
    "UserId":"62f4013cb7fcb386648da55c",
    "itemName":"First Entry",
    "discription":"Holds some content as descriptional text"
}